### ISSUE TITLE
Show more bounties

### ISSUE THREAD

**Issue by Giszmo** [diamsa/nostrbounties#16]
Currently only 10 bounties are shown while 30 fit my vertical screen. Please make the site load another 10 whenever that button to load more is visible for more than 2s - or better go in increments of 50.

**Comment by diamsa** [comment]
The idea is to load more bounties. In fact, it was that way weeks ago, but I have trouble with the relays that query bounty's current status. There's only one relay that is storing the __in progress__ statuses, and it is limited to 10 concurrent subscriptions. That stops me from loading more bounties.

I am testing new relays to fix it, i hope to add them soon.

**Comment by Giszmo** [comment]
But ... why do you need more than 10 subscriptions? Put all filters into one subscription. Big social clients typically work with less than 5 subscriptions. Other than that, this is a perfect example of ["damn relay operators! Stop putting up arbitrary limits!"](https://snort.social/e/note1242yskvruj0wr9nrhdseswdhntrsnqfd6ujluvq9lv7vyw9w4luq66u549)

**Comment by diamsa** [comment]
I am doing it because the status filter needs the identifier of the bounty, so a new subscription with this element is needed for each bounty in order to get the status. I think it can be improved.

And, yes, it is sometimes frustrating dealing with these types of relays.

**Comment by Giszmo** [comment]
I can't follow. This client is not very dynamic, so closing channels once the `eose` is received, should be ok, allowing for job queues but also, putting all queries in one subscription and sorting events as they are being  received should work. Mind sharing 2 queries you fail to put on the same request?

You can have a channel with request `{greenStuff}, {redStuff}` and you get back green or red stuff, so you have to sort out and the stuff that's both green and red you have to feed to both consumers but maybe I'm missing something ...

**Comment by diamsa** [comment]
hey @Giszmo! I'm sorry I couldn't answer quicker. I just want to tell you, you were right, there was a better way of implementing the subscription to relays without having to create a ton of channels.

I have the changes ready, but I am gonna push them once I solve other minors bugs I found ;)
