### ISSUE TITLE
Something is off in the naddr format. 

### ISSUE THREAD

**Issue by vitorpamplona** [diamsa/nostrbounties#2]
This post https://nostrbounties.com/b/naddr1qpqrwve3v56nxv3cxv6nvdeex9jrzctyvdskgcnyvcck2ce5xcekydrpvvungvf4v33njwfkvcmnjcf4vvmn2vrpxqenscnxxe3rwef4xgpzq3huhccxt6h34eupz3jeynjgjgek8lel2f4adaea0svyk94a3njdqvzqqqr4gukgahaj 

has the following nddar `naddr1qpqrwve3v56nxv3cxv6nvdeex9jrzctyvdskgcnyvcck2ce5xcekydrpvvungvf4v33njwfkvcmnjcf4vvmn2vrpxqenscnxxe3rwef4xgpzq3huhccxt6h34eupz3jeynjgjgek8lel2f4adaea0svyk94a3njdqvzqqqr4gukgahaj `

which converts to: `30023:46fcbe3065eaf1ae7811465924e48923363ff3f526bd6f73d7c184b16bd8ce4d:731e5328356791d1adcadbdf1ec463b4ac9415dc996f79a5c750a038bf6b7e52`

However, the post has the following tags. 

(2) ['t', 'bounty']
(2) ['title', 'Make Nostr Relay that applies limits based on proximity to a group of accounts']
(2) ['reward', '2172215']
(2) ['published_at', '1679509418']
(2) ['d', '1679509418']
(2) ['t', 'development-bounty']
(2) ['rootId', '11fbe77018024da5770f4193b3211873621827ec7635d97a0a9864274eaca372']

The `d` tag (`1679509418`) is not the same as the `d` tag in the naddr (`731e5328356791d1adcadbdf1ec463b4ac9415dc996f79a5c750a038bf6b7e52`. 

It should have the following address: 

`naddr1qq9rzd3h8y6nqwf5xyuqygzxljlrqe027xh8sy2xtyjwfzfrxcll8afxh4hh847psjckhkxwf5psgqqqw4rsty50fx`

which converts to: 

`30023:46fcbe3065eaf1ae7811465924e48923363ff3f526bd6f73d7c184b16bd8ce4d:1679509418`

**Comment by vitorpamplona** [comment]
Also, the naddr seems to be changing from time to time. That should not happen.

**Comment by vitorpamplona** [comment]
Found it: 

When the system calls
```js 
let naddr = nip19.naddrEncode({
    identifier: id,
    pubkey: pubkeys,
    kind: 30023,
  });
```

The `identifier` field is supposed to be the `d` tag and not the `event.id` as in today. 

It should be a quick fix if you don't mind URLs changing (which they already do today)

**Comment by Giszmo** [comment]
So my edits resulted in me creating multiple bounties? I do not approve that! :D

**Comment by diamsa** [comment]
> Found it:
> 
> When the system calls
> 
> ```js
> let naddr = nip19.naddrEncode({
>     identifier: id,
>     pubkey: pubkeys,
>     kind: 30023,
>   });
> ```
> 
> The `identifier` field is supposed to be the `d` tag and not the `event.id` as in today.
> 
> It should be a quick fix if you don't mind URLs changing (which they already do today)

Hey @vitorpamplona! thanks for informing me about the issue. I am going to solve it as soon as possible.
