### ISSUE TITLE
Share Button Bug

### ISSUE THREAD

**Issue by BitcoinBrief** [diamsa/nostrbounties#20]
The "share bounty" button on bounty posts leaves off the ".com" in the link produced.
![Screenshot 2023-05-22 181617](https://github.com/diamsa/nostrbounties/assets/115094037/0dbc8799-2e75-4acd-96e1-b52e6bad54a7)

For example:  "https://nostrbounties/b/naddr1qq9rzd3cxsmnsdpjxc6qygxs3jf3986ucff2jqtm75heppgxpvg8vcs2trxkjg5mx83h8m7vnupsgqqqw4rsxfs3dy"

I posted a [bug bounty](https://nostrbounties.com/b/naddr1qq9rzd3cxsmnsdpjxc6qygxs3jf3986ucff2jqtm75heppgxpvg8vcs2trxkjg5mx83h8m7vnupsgqqqw4rsxfs3dy) for this one.

**Comment by diamsa** [comment]
hey! thank you for reporting it. I'll fix it asap ;)

**Comment by BitcoinBrief** [comment]
Thanks!
