### ISSUE TITLE
Bounty not found after marking as in progress

### ISSUE THREAD

**Issue by rolznz** [diamsa/nostrbounties#22]
https://nostrbounties.com/b/naddr1qq9rzd3ex5unjd3hxv6qygq4kh8keh6068qz729uec83jl904exgclrx503wywhelesssaf3tcpsgqqqw4rs4x5p2f

![image](https://github.com/diamsa/nostrbounties/assets/33993199/25fecae9-5d74-440f-a95c-46e6f3ec1440)

**Comment by psic4t** [comment]
Can't finish or pay the bounty. Any news?

**Comment by rolznz** [comment]
@diamsa is this project still active?

**Comment by diamsa** [comment]
Hi, I'm not working on this anymore
