### ISSUE TITLE
Getting connection close before established errors

### ISSUE THREAD

**Issue by vicariousdrama** [diamsa/nostrbounties#23]
With recent update changing timeout from 15 seconds to 2, Im now seeing this on nostrbounties.com when trying to view some bounties and cant update their progression status.

![image](https://github.com/diamsa/nostrbounties/assets/88121568/29102fb0-bcd5-4287-960c-3191676caf3e)

**Comment by diamsa** [comment]
Hey Vic, Yes I am seeing the error. In another issue I said I wasn't working on this project, but it seems the app is really buggy. I'll try to fix all these problems during the weekend.
