### ISSUE TITLE
Document Event Structure

### ISSUE THREAD

**Issue by jeffreyweier** [diamsa/nostrbounties#24]
https://nostrbounties.com/b/naddr1qq9rzdesxqmrsvfexgeqygppksv3qtdgls96jpyy4mynf064k74u7a0wmvu3yn5dwhjfraq6tcpsgqqqw4rs8z0zyv

The nostrbounties.com website is a nostr client for finding and posting bounties to nostr. To improve collaboration and compatibility with other bounty systems, it would be helpful if the structure of events were documented to avoid the need to reverse engineer/infer the structure

To satisfy this bounty,

- a markdown file should be added to the code repository for nostr bounties (https://github.com/diamsa/nostrbounties/tree/master)
- a section of the file should explain the event structure and provide sample json for a new nostr bounty, including the required tags for association
- a section of the file should explain event structure and provide sample json for adding to a nostr bounty
- an optional section can address historical/deprecated formats but this is NOT required to satisfy the bounty

**Comment by diamsa** [comment]
Hi Jeff, I don't know why I did not get any notification of your pull request. I merged it. Thanks
