### ISSUE TITLE
Subscribe to the `a` tag not the `e` tag to get the added pledges

### ISSUE THREAD

**Issue by vitorpamplona** [diamsa/nostrbounties#5]
The e tag will change when the author changes the text. Once it does the pledged amounts by other people disappear. You can filter for the `a` tag instead.  

https://github.com/diamsa/nostrbounties/blob/d01b351397af67f148c7ec9c9c3b41a0e6284980/src/pages/bountyFullInfo.tsx#L95

**Comment by diamsa** [comment]
The issue is fixed, thanks again. I realized I was creating another tag called _rootId_ without need. If you find something else that needs to change, let me know, please.
