### ISSUE TITLE
Editing bounties is broken

### ISSUE THREAD

**Issue by fiatjaf** [diamsa/nostrbounties#6]
When I click "post bounty" after editing a bounty I get this:
![2023-03-26-072211_1023x745_scrot](https://user-images.githubusercontent.com/1653275/227769501-bb6d49b2-1953-4f34-b30e-9ef01408ffeb.png)

**Comment by diamsa** [comment]
this error occurs when you don't type a new value for the title or the content. Did you change something and displayed the error?

**Comment by fiatjaf** [comment]
I change the title, then clicked the button.

**Comment by diamsa** [comment]
Great, let me check

**Comment by diamsa** [comment]
> I change the title, then clicked the button.

fixed fiat!
